
export const EMPLOYEES_FETCH_REQUESTED = 'EMPLOYEES_FETCH_REQUESTED';
export const EMPLOYEES_FETCH_SUCCEEDED = 'EMPLOYEES_FETCH_SUCCEEDED';
export const EMPLOYEES_FETCH_FAILED = 'EMPLOYEES_FETCH_FAILED';

export const EMPLOYEE_UPDATE_FAILED = 'EMPLOYEE_UPDATE_FAILED';
export const EMPLOYEE_UPDATE_REQUESTED = 'EMPLOYEE_UPDATE_REQUESTED';
export const EMPLOYEE_UPDATE_SUCCEEDED = 'EMPLOYEE_UPDATE_SUCCEEDED';

export const DEPARTMENTS_FETCH_REQUESTED = 'DEPARTMENTS_FETCH_REQUESTED';
export const DEPARTMENTS_FETCH_SUCCEEDED = 'DEPARTMENTS_FETCH_SUCCEEDED';
export const DEPARTMENTS_FETCH_FAILED = 'DEPARTMENTS_FETCH_FAILED';
export const DEPARTMENT_UPDATE_FAILED = 'DEPARTMENT_UPDATE_FAILED';
export const DEPARTMENT_UPDATE_REQUESTED = 'DEPARTMENT_UPDATE_REQUESTED';
export const DEPARTMENT_UPDATE_SUCCEEDED = 'DEPARTMENT_UPDATE_SUCCEEDED';
